#!/usr/bin/python

import sys
import basNetAna as net
edgeList = net.file2graph(sys.argv[1])
#Total vertexs and links
dicVertexs,dicInDegree,dicOutDegree = net.totalVertexsAndLinks(edgeList)
#Average out-degree and in-degree
net.averateDegrees(dicInDegree,dicOutDegree,dicVertexs)
#Clustering coefficient
net.coefficient(dicVertexs,dicInDegree,dicOutDegree,edgeList)
#Assortativity
net.assortativity(edgeList,dicInDegree,dicOutDegree)
#Radius and Diameter
net.radiusAndDiameter(dicVertexs,dicOutDegree)
